import Head from 'next/head'
import Image from 'next/image'
import LebronLakersImg from '../public/LA-lebron.png'
import LebronMiamiImg from '../public/miami-bron.png'
import LebronCleveland1 from '../public/cleveland-bron-1.jpeg'
import LebronCleveland2 from '../public/cleveland-bron-2.jpeg'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useState, useEffect} from 'react'
import PlayerInfo from './components/PlayerInfo'
import SeasonSelector from './components/SeasonSelector'
import {SEASONS} from './constants'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //Use State
  const [player, setPlayer] = useState('')
  const [loading, setLoading] = useState(true)
  const [season, setSeason] = useState('2022')

  //Use Effect
   useEffect(() => {
    getPlayer(season)
  }, [season])

//Request functions
  async function getPlayer(season){
    const response = await fetch(`api/getLebron?season=${season}`)
    const data = await response.json()
    setPlayer(data)
    setTimeout(() => {
      setLoading(false)
    }, 500)
  }

  const handleChangeSeason = (event) => {
      let season = event.target.value
      setSeason(season)
  }

  return (
    <>
      <Head>
        <title>Lebron James Stats Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.playerSection}>
          <div className={styles.player} onChange={handleChangeSeason}>
            <div>
            {loading ? 'Loading...' : <MainImage season={season} team={player.team} loading={loading} />}
            </div>
            <SeasonSelector SEASONS={SEASONS}/>
            <PlayerInfo firstName={player.firstName} lastName={player.lastName} position={player.position} points={player.points} assists={player.assists} rebounds={player.rebounds} blocks={player.blocks} steals={player.steals} team={player.team} loading={loading}/>
          </div>
      </main>
    </>
  );
}

const MainImage = ({ season, team }) => {
  const seasonNum = parseInt(season);
  let image = LebronLakersImg;
  if (team === "Cleveland Cavaliers" && seasonNum > 2014) {
    image = LebronCleveland2;
  }
  if (team === "Cleveland Cavaliers" && seasonNum < 2010 ) {
    image = LebronCleveland1;
  }
  if (team === "Miami Heat") {
    image = LebronMiamiImg;
  }

  return (
    <div>
      <Image src={image} width="100%" height="80vh" alt="Image" />
    </div>
  );
};
