import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
import Test from '../pages/api/Test'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //Player Name
  const [name, setName] = React.useState('')
  console.log("Name:", name)  
  React.useEffect(() => {
    getApi()
  }, [])

  async function getApi(){
    const response = await fetch('api/hello')
    const data = await response.json()
    setName(data.name)
  }

  //Player's Teams
  const [team, setTeam] = React.useState('')
  console.log("Team:", team)

  React.useEffect(() => {
    getTeam()
  }, [])

  async function getTeam(){
    const response = await fetch('api/teams')
    const data = await response.json()
    setTeam(data.teams[3])
  }

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Info about {name}</p>
        <p>Team: {team}</p>
        <p>Real soon</p>
      </main>
    </>
  )
}
